### ISSUE TITLE
Invalid profile

### ISSUE THREAD

**Issue by wahyudierwin** [mooshak-dcc/mooshak-2#1]
I just want to ask about "invalid profile".

After installing the Mooshak through docker (I used the starter tag), then I added an user in the "proto_icpc" contest with the student profile. Then I tried to login using the newly added user. It said "invalid profile" although I was sure that the password was correct.

What should I do?

Thanks.

**Comment by josepaiva94** [comment]
How have you added the user?

**Comment by wahyudierwin** [comment]
Thanks for the reply.

Actually the profile "student" is not found. As I changed into another profile, the problem is solved.

I will close the issue.
